version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-tu-clave-secreta-por-defecto}
    volumes:
      - ./telegram_messages.json:/app/telegram_messages.json
    networks:
      - monitoria-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: monitoria-frontend
    ports:
      - "8080:80"
      - "80:80"
    depends_on:
      - backend
    volumes: [] #sin bind mounts
    stdin_open: true
    tty: true
    restart: always
    networks:
      - monitoria-network

networks:
  monitoria-network:
    driver: bridge
