FROM python:3.9-slim

WORKDIR /app

# Instala curl para el healthcheck
RUN apt-get update && apt-get install -y curl

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5001

CMD ["python", "app.py"] 